# Generated by Django 4.1.1 on 2022-09-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 1), ('librarian', 2)], default='student', max_length=50),
        ),
    ]
