# Generated by Django 4.1.1 on 2022-09-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_transaction_transactiondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
