# Generated by Django 4.1.1 on 2022-09-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_transactiondetail_return_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='borrowed_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='returned_at',
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='return_deadline',
            field=models.DateTimeField(default=None, null=True),
            preserve_default=False,
        ),
    ]
