# Generated by Django 4.1.1 on 2022-09-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rename_qty_book_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('ongoing', 'ongoing'), ('complete', 'complete')], max_length=50, null=True),
        ),
    ]
